# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskhandler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_file_location',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_finish_time',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='task_start_time',
            field=models.TextField(default=''),
        ),
    ]
