# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskhandler', '0002_auto_20160110_1221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tasks',
        ),
    ]
