# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taskhandler', '0003_delete_tasks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.TextField(default='')),
                ('task_start_time', models.TextField(default='')),
                ('task_finish_time', models.TextField(default='')),
                ('task_file_location', models.TextField(default='')),
            ],
        ),
    ]
